SystemOrganization addCategory: #'Golgotterath-Core-Tests'!
SystemOrganization addCategory: #'Golgotterath-Core-Tests-Base'!
SystemOrganization addCategory: #'Golgotterath-Core-Tests-Entity'!
SystemOrganization addCategory: #'Golgotterath-Core-Tests-GameBoard'!
SystemOrganization addCategory: #'Golgotterath-Core-Tests-GameMap'!
SystemOrganization addCategory: #'Golgotterath-Core-Tests-Manifest'!
SystemOrganization addCategory: #'Golgotterath-Core-Tests-Sprite'!
SystemOrganization addCategory: #'Golgotterath-Core-Tests-Strategy'!
