SystemOrganization addCategory: #'Golgotterath-Core'!
SystemOrganization addCategory: #'Golgotterath-Core-Base'!
SystemOrganization addCategory: #'Golgotterath-Core-Manifest'!
SystemOrganization addCategory: #'Golgotterath-Core-Sprite'!
SystemOrganization addCategory: #'Golgotterath-Core-Strategies'!
SystemOrganization addCategory: #'Golgotterath-Core-Tile'!
SystemOrganization addCategory: #'Golgotterath-Core-View'!
