"
Collection of floor and wall tiles for dungeon
"
Class {
	#name : #Tiles,
	#superclass : #Sprite,
	#instVars : [
		'tiles'
	],
	#category : 'golgotterath'
}

{ #category : #acccessing }
Tiles class >> imageSource [
	^ 'iVBORw0KGgoAAAANSUhEUgAAAgAAAADACAMAAABF0StVAAADAFBMVEX/AADgAAC/AACgAACA
AABfAABAAAAwAAAfAAAXAAAPAACAQECgUFC/X1/gb2//gID/QADgOAC/MACgJwCAHwBfFwBA
DwAwCwAfHwAXFwAPDwCAgECgoFC/v1/g4G///4D/gADgbwC/XwCgUACAQABfMABAHwAwFwAA
HwAAFwAADwBAgEBQoFBfv19v4G+A/4D/vwDgqAC/kACgdwCAXwBfSABAMAAwIwAAHx8AFxcA
Dw9AgIBQoKBfv79v4OCA/////wDg4AC/vwCgoACAgABfXwBAQAAwMAAAAB8AABcAAA9AQIBQ
UKBfX79vb+CAgP+A/wBv4ABfvwBQoABAgAAwXwAfQAAXMAAfAB8XABcPAA+AQICgUKC/X7/g
b+D/gP8A/wAA4AAAvwAAoAAAgAAAXwAAQAAAMABfMDBAHx8wFxeAX1+gd3e/kJDgqKj/v78A
/4AA4G8Av18AoFAAgEAAXzAAQB8AMBdfXzBAQB8wMBeAgF+goHe/v5Dg4Kj//78A//8A4OAA
v78AoKAAgIAAX18AQEAAMDAwXzAfQB8XMBdfgF93oHeQv5Co4Ki//78AgP8Ab+AAX78AUKAA
QIAAMF8AH0AAFzAwX18fQEAXMDBfgIB3oKCQv7+o4OC///8AAP8AAOAAAL8AAKAAAIAAAF8A
AEAAADAwMF8fH0AXFzBfX4B3d6CQkL+oqOC/v/+AAP9vAOBfAL9QAKBAAIAwAF8fAEAXADBf
MF9AH0AwFzCAX4Cgd6C/kL/gqOD/v///AP/gAOC/AL+gAKCAAIBfAF9AAEAwADD////g4OC/
v7+goKCAgIBfX19AQEAfHx//AIDgAG+/AF+gAFCAAEBfADBAAB8wABfw8PDPz8+vr6+QkJBv
b29QUFAwMDAPDw9+WUildV3Jj3HlooL/tZH/0q5nVB6Abx+qiDS/oEDyw0344F/8/Jl0aFeR
h22qmoHgv6DPqFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHa2t8
2GZOAAABAHRSTlMA////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////Cpf0
PAAAFdlJREFUeF7lnWuS2zgMhOf+R7Ml8ndGlniHPcHyIeoBEWIDsjMTUalNpTZuf4BIkQTs
TH/d/XJfbV+N5+/C1X7+Taff8C1oPH+3vdrP/+/j35zMlfR/4BY0nv97mfIUXOlqP/+/v/i8
eSm7kv5fvAWN5/9epjwFd3a1n78cf3HvcW9MH3g7V7vaz1+Ov7j3uDemX3k7h1zt5y/HX9x7
3BvTP3k7h17t5y/HX9x73BvTZ97OSa7285fjL+497o3pF97NCa/281fgzzRD95nNp3z1o4Z/
pr+Wv/vY5ovFLx3+0/x1KYzjc/jM5nO8xtFaHZ/XX8nffXTzrccvHf7T/LUpDN04Ds/PbD50
9lprRi2f0+vzdx/ffM/jlz/9Z/mrJ0A3PAbkKbx6A8LsHfvRaPmcXr2Tf/zsUYlf8fTz+Vf3
Ul7on7/h6YdAq0f5PvyxL24BGJ/Tg7ffHOOVDMF5/oiexi/ln+WfbyR7C8eeF4ab/6gMwZke
5Y8mJtFr+Zweuv19ceLBQ3CeP6an8Uv5fP6bGzkUF1ITFg92BvsVeFieQoUe5Yff+7FQBYB8
Tl+/feX4Ew8ZgvP8UT2NX8rn8l8TijfyuJdG+cgfHsIRLCqVepQfDjDlKgDjc/ov5PYV4s88
o9RL+TR+KZ/Nf3sjH4eFtB9re0eciUmp0qN8nwS7BSB8Tn++kPLxr7xRpZfyafxSPpf/Gsiw
PEvD/uRY2QK6VanRo/wQ/uQnsZbP6cPrv05PzuX4tzyr0Ev5NH4pn8t/cyPTQWqtq/tl2RhP
hP3Ydc9nUOr0KD/82ZhjOYXyOX16/RdbN3Px73mjWC/l0/ilfC7/3al2eIxjrqtz3ZjPj5zu
+9uYx3MORqFH+eM4GVd4klA+p19ez9TNXPwHnlAv5dP4pXwu/+WKb/NcT9SbvSP+zs5gvxMZ
H4BWj/LN6ML/MVo+p1/7CGOxbubipzypXsqn8Uv5XP6bPW0IC+ljqavnujHsHf3rtBH0PXT9
qNWj/Gny+fR20vI5/baPYAt1Mxf/gSfUS/k0fimfy3+zl/obGd8yzapcNwZ539uTVnB4dTdo
9Sjfb2Z+EXuNWj6n3/cR+kPdzMVPeVK9lE/jl/K5/DdLaXjLx3K2zAcI/ya9mc62AI8dvzut
HuWH+fwqbgEYn9PTPgKtm7n4KU+ql/Jp/FI+l//2MNKNZj5bxgoz1Y1+3lQaQd/fAa3Vo3zn
E+r7adLyOT3tI9C6mYv/yJPppXwav5TP5b+rRzs/f3JdnevGsHj0Iy/0+69JGp0e5Rs/jY0t
lWMYn9eTPgKpm7n4KU+ql/Jp/FI+l//mUBN3lSHX1bluDEeHyfI95O9nev60epRvplDaHJ8k
lM/paR+B1s1c/JQn1Uv5NH4pn8t/s6eF+fQ9rHV1qhv9W02VzwI6fxDrtXqU7xsbr/F1bGSg
fE5P+wi0bubiP/Jkeimfxi/lc/kvlwkLSCin5ro6141e7t+EX8LCKbx7xMVIpUf56Sw7GS2f
0x/7CPu6mYuf8qR6KZ/GL+Vz+e96235F6XJdnevG1yvMIXNSBXz782hYgnV6lB8OMD6tScvn
9LSPQOtmLn7Kk+qlfBq/lM/lv6lHn3Em5bo6142hiPAnipMEnnEn0upR/jSXMlo+p6d9BFo3
c/FTnlQv5dP4pXwuf1qPmlxX57pxSt2kif8c32uGeAxR6VG+CUvb9Oq1fE5P+wi0bubipzyp
Xsqn8Uv5XP5rIN/5JJnq6lw3mniA4D9HTk+bn31KPcpP+5jptXxOT/sItG7m4qc8qV7Kp/FL
+Vz+2952Z+KukurqXDf6xSPKzw9vYRnS6VH+FMqawnfrUD6np30EWjdz8VOeVC/l0/ilfC7/
7Uz088kvJnNdnevGMJNeJ4eH2IB4hN1Hp0f5xvRhbhstn9PTPgKtm7n4KU+ql/Jp/FI+l//+
RqaPF2JdnevGyc+k6WTvCDc/HEa0epTvN7PQ2Jy0fE5P+wi0bubipzypXsqn8Uv5XP6bPS2+
zZDr6lw3+pnkhf2LTcCjw3lUq0f5c39r0vI5Pe0j0LqZi5/ypHopn8Yv5XP5b/fSISwpua7O
dWP4coE5+RDhGT+JigGo9Cg/nGvDR51aPqenfQRaN3PxU55UL+XT+KV8Lv91L/JHikf8hlmq
q6e1lAizqj/5MOMZZqJWj/JDU8OXs72Wz+lpH4HWzVz8lCfVS/k0fimfy397qk1fLJjr6lw3
xkry9EuhsQHZa/UoP4Tv97NJy+f0tI9A62YufsqT6qV8Gr+Uz+W/2Uu71Eyc6+pcN85fLTz5
SteYyhC1HuOH5az8vRqMz+lpH4HWzVz8lCfVS/k0fimfv3/LkuJvZFxGUl2d68a4klS+0RPQ
V/QI3y9k7gqf09M+Aq2bufgpT6qX8mn8Uv7Z/VsOIyYvpKG0mutGf3TwC0ltD0+HEb2+zj8/
Rtb5nJ72EWjdzMVPeVK9lE/jl/Krx/DRPENj0eS6OteN/uTY+xNl/Xv9/6ie9hFo3czpKU+q
/y38/V769DvJXFfnutGvIy/sR5z8m3raR6B1M6/f8+T638GnJ+pHrqtz3RjODl831tM+Aq2b
z/Rbnkb/G/ilE3Wsq3PdKJL/g3raR6B187l+5en0P89n6/pq3XgTPe0jwHXzTfR8XV2rG2+j
3/cR4Lr5Nnqmrq7WjTfSb/sIcN18I31xYVEtHv+sfu0jwHXzrfTtX0tdLaibb6Vv/8p1taRu
vpW+/SvW1cK6+Vb69q+vq7fvX9e3f7V/tX+1f7V/tX+1f7V//eOXaz//ptNv2z+/9fwb989v
Pf8f9s9vPf/G/fNbz79x//zW82/cP7/1/G/ln996/o3757eef+P++a3n37h/fuv5N+6f33r+
v98/311JX2Wg31D+Gg3i3//G9A9vh/DRcOTxu49tvtjbOc2lwfNBY/79b0yfvB3GR8KRx+8+
uvnW385pLw2eXwEw//43pr97O5R/1Q3+asTvz99dud63l6H+/df30vK74fyzaNwv3XxP3s25
984A7V6O+fe/5yxR8uOX8Dk/f81Nk/n36zdfLn4Nn8s/30jVECL+/dhZAh/CrR+/jF/y89cN
ocS//9rmW45fxy/lv7mRg2Ihr/v3Y1MA1VM/fimf6rVDiPv3n+cvH74Uv5ZP818HgPHfryVQ
8++HJwCop378Uv7Bz187AUD//sunTyZ+Lf+Q//ZGPqoLaV/8Ua28f39dL+VTP34pn+plC2k/
HuMdVXotf/UF1PFp/msgBf/9w94xln7ePu/fj+ilfOrHL+VT/Zl//1n8iH8/kr+Un+PX8mn+
m4Gk/vul2VP33ZPqpXzqxy/lUz3v338ef92/H8tfys/xa/k0/92pdutHX549uH8/qpfyqR+/
lE/1nP9+Lf6afz+av1S/+gLq+DT/5Tr60e/rRm7v4Pz7Ub2UT/34pXyqL/vvH+tmGv+5f39d
r+Xn+LV8mv9mDz760e/qztmPvpBA2b8f1Ev51I9fyqf6kv9+se4m8Z/59yN6LT/Hr+XT/Dd7
ecmPfq0bsx/9cQkr+/ejeimf+vFL+VR/9N8v1800ft6/H9Nr+Tl+LZ/mv1nKMT/6o67s34/q
pXzqxy/lU/3h9UzdTONneaBey8/xa/k0/+1hBPKjPybA+fdjeimf+vFL+VR/7COMTN29j5/j
oXotP8ev5dP8d/Uo4kd/LGPK/v2oXsqnfvxS/lF/7CPYQt1M42d5oF7Lz/Fr+TT/zSEM86M/
lIGMfz+ql/KpH7+UT/XlPsJ4qJtp/BwP1Wv5OX4tn+a/2YMxP/pS/V7278f0Uj7145fyqZ7r
Ixzr7n38HA/Va/k5fi2f5r9cqB99qQoo+fejeimf+vFL+VTP9RFo3Uzj53mYXsvP8Wv5NP9d
Lx7xoz8mUPbvR/VSPvXjl/Kpnu0jkLqZxs/xUL2Wn+PX8mn+m3oU86MvHN6K/v2oXsqnfvxS
PtVzfQRaN9P4OR6q1/Jz/Fo+zZ/Wo1U/+uPn+GX/flQv5VM/fimf6rk+Aq2bafwcD9Vr+Tl+
LZ/mvwYC+tEfl+6yfz+ql/KpH7+UT/V8H2FfN9P4OR6q1/Jz/Fo+zX/bi4f86MuHt6N/P6qX
8qkfv5RP9VwfgdbNNH6Oh+q1/By/lk/z385EyI+++EWOgn8/qpfyqR+/lE/1XB+B1s00fo6H
6rX8HL+WT/PfDyTgR1/4MKPo34/qpXzqxy/lUz3fR9jXzTR+jofqtfwcv5ZP89/swZgf/SEB
xr8f1Uv51I9fyqd6ro9A62YaP8dD9Vp+jl/Lp/lv93LIj770YUbJvx/VS/nUj1/Kp3quj0Dr
Zho/x0P1Wn6OX8un+a97EehHX/gwo+jfj+qlfOrHL+VTPddHoHUzjZ/joXotP8ev5dP8t6dw
yI/++GFG2b8f1Uv51I9fyqd6ro9A62YaP8dD9Vp+jl/Lp/lv9nLMj75wfi/69+N6Gf/oxy/j
Uz3XR6B1M42f46F6LX/xBVTyj/dvWdIwP3ruG71X9BJ+yY9fwqd6ro9A62YaP8dD9Vp+jl/L
L92/5TCC+NGz3+i7pL/qx4/zqZ7rI9C6mcbP8VC9lp/j1/LL9+8L96Nnl/C/pH+3nz7XR6B1
M42f46F6LT/Hr+Wf+ApifvQn/8D7r+jf7afP9RFo3XyMv8zD9Tr+Gr+Of+oriPjRn/2Qh7+h
f7efPtdHoHVzKf4ST6LX8Lfxa/gVY7m6H/35D3r5vP7dfvpcH4HWzeX4jzyZXs7fxy/nV30F
W/PT5/oItG6+q/6rVtff30+/3Ec41N231Vfq+hb89Et9BFo331l/Wte34ad/7CPQuvne+pO6
vBU/fVpXA3XzrfR8Xd2Mn/6+robq5lvpmbq6JT/9bV0N1s230hdnVVt++mtdDdfNt9K3fy11
taBuvpW+/SvX1ZK6+Vb69q9YVwvr5lvp27/8Qnpt8azrz6+f1rd/tX+1f7V/tX+1f7V/NX45
hX/9nfjtD7/Q+VBulfib+e0Pv9D5UOeW+Vv57Q+/0PlQb5j6G/ntD7/Q+fCaZ+5v47c//ELb
v2ueub+N3/7wCy2/rtsm/yZ++8MvdH17j3P2b+G3P/xvNz78l/jtD7/C9+59Q/DT/PaHX+l7
954h+Gl++8N/wffub/jnf5bf/vBf9L37tH/+Z/ntD3/Vb77ue/dJ//zP8tsffsSvHvC9+5R/
/mf57Q8/5DeP+d59ooz7LL/9C/SbR33v3u2f/3F+69fQ/Qf61aO+d9I6/mf5zV/hqfkP8JuX
+N5J6/if5Le/AsQ6+r+q37zM905ax/8cv/mL85+PNz5vw6jvXXr9qX//b+O3vwUU/efTLXcm
Xg71vcuvP/PvF/Ft/PeNOH/yLzdWxG/+KvnPz3W3H89QffsRxXzvwvhHgTvx75fw04+59CMK
8m18+eQk/PbPAAf/+aXujqOZRhTxvZvnS7zTvH+/gO+sH8/wy2L8zctxfvtbAOu375bxHB3i
e+eWlxvH+/cL+OGBNmlEIX6cACYuGTi//S2A89u34YHu468wolXfO7d5uV8COP9+nO/SeIYp
YBG+XV7uTw0wv/0tgPPbXyeA/1+u7nvn4gvzBGD9+3H+MgHCbgDw7fziOAFgfvMX77e/DP/4
8itA1ffOBYOaPAUs698P8/0RsJ/SfArWt3W+7dOM9TL/UpTf/MX57dt0N8Pw+1+u7nvn4gvT
FIjPatm/H+aHCWDWCVDn5wlgwgSA+eXrz5/Ho5UtgPHb302AztV971y3mwCcfz/MzxPg1YUJ
APD9BOheywRA+eXhDwYMjUwBzm/fxuEPY/oaBmPrvnfWDMMrrQJeajn/fpjv3DMc3HozdfGH
Xlb51r/Qv9wv974TDPO54e/8ztTEFOD89pcJEPyH/BZQ9b0LxgRpCsQJwPn3w3znXta8/CMd
znQIP5wa/YLxMtbvFDCfXo+wHw3PZ3DgG1qYApzfvp13/1f4aYO+yVr1vQveVMbMa8BoOf9+
mO8HMRxEui6eAQB+OAN03Xx+gPmH4Y8Pf/hxq6GZ1MAU4Pz2lwkQVs7O1n3vbNdvJJbz74f5
sQoIu3fX9Rbh276LZ/5YBcD8/YE0DP8Qn/40ARo4C3B++3YeSz+afgSmuu/dFF63iCzn3w/z
4wSIe/fYjQh/DIPtV4pprgIwPhn+Z5ce/CFe/i18jfr8/r5zGcj47S8TYAj2u7bue+cPDX0+
BvoJwPn3w/xYBYRKxE8Gi/D9i6ZUNU7xEIjxt8PvRzut/XHowyzonmk23HgKcH77dh1+/1S5
uu9d6NWsU8By/v0w37nYB5z7AAB/7gNEr0wH89fhn5/6+QDQdUPeBOKfbjsFOL99a5bh98+e
q/veuWBSnKdAMKkp+/fDfJdawXMfAODPfYDYCnYwf1n884P/zH/uhuWPcXLcdApwfvt+AuTh
N71vBFV971wXyr95CoQ+QNm/H+bPE8CPne8DIPzQB5g/PoxbAMbPw991y94/n/9SITjvAbEv
cMspwPntW/PnTxh+f/AeulDW13zvrPHFvH+5nwJ//vgJwPj3w3y3fho4WYRvp/XTQAfz/fCv
dX968PMxcF4Mtn2BG04Bzm/fT4DBTK+wDoQzQN23LpwBwrP/mszwJ34WUPTvh/lpAqRzgEX4
tp+Hf5w/CwD434e6Py0CaTmY/9/u7283BTi/fX/LwvCH8QyNoLpvXWwEZclkOf9+mO9c/oZH
mAAAf5kAUYrwd3X/MvpxwV86AZu/fz7veBbg/Pb9GcCPZj9/uuPqvnVu/uyoj0LL+ffDfBcb
emkVsAjf5i+EBSXAL9T984m/65aj3/r38TRww74A57cfq4Axjag/ftV96+I3gsa5Gxi2gLJ/
P8yPz/E8BSzCt3n4g7DKL9T9afzTOD/nLtCuL/Bc+wKv+0wAxm/fms3wOwP41rnNFEhVQMm/
H+a79MvF7wYj/Ph9YDfLqvxwKNzV/fPRfykCu/lUuOkLzH8fO473qQI4v/3lo/3wFCLvFJ6+
5UsElvPvh/lpHKdpkvCnacoToMpPU6B7rvv+Mx/41wbA8e+H8V5uHJzfvl2G38D/msaYZQpY
zr8f5qfxD19OlvCtTTMA4s+rwFIADPkw8Fz+3JG+wN2G/+hfn/3m7Sgd/u0UGC3n3w/zw+f7
VsO34fsDIH+dAuvI5//2UyDuEt14Py8e1m9fMfybKWC1/v3L69M/C1TxXfpGEMSfN4LlnL/U
/c9teZA+GRrvacVU9tu3quFfpoDV+vcvfGf1fOsEfD8Fwolv/vAn1/1pOYh1f+oL3HX4lzqa
+O1rb38eAq1//0/wl4pg3xdY6v7hjnv/oY4mfvvm0j+kNkbr3/8z/DAFzur+8f4+fFf9+q++
30/zD32Bu9b9p2eBS379V9/vp/nhLNBA3V+pCB5XDduvvN9P89MUuHndX22o2p98v5/m7/oC
XTOLf/tXsS/Q/vC3OwVuXve3f9WnQPvD3/gUqA3/19e//dv/soxI491cjk0AAAAASUVORK5C
YII='
]

{ #category : #initialization }
Tiles >> initialize [
	| floor |
	super initialize.
	self loadSpriteImage: (self imageSource)  spriteWidth: 64 spritesPerRow: 8.
	tiles := Dictionary new.
	floor := spriteImages at: 15.
	tiles at: 'floor' put: floor
]

{ #category : #initialization }
Tiles >> tile: name [
	^ tiles at: name. 
]
